{"uuid": "dc4917de-1b85-482f-8ad1-f985961a9cc2", "children": ["421b846b-7f1e-4e87-86a4-a1e4cdeff51c"], "befores": [{"name": "open_browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: <html>\r\n<head><title>401 Authorization Required</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>401 Authorization Required</h1></center>\r\n<hr><center>nginx/1.14.2</center>\r\n</body>\r\n</html>\r\n\n\n", "trace": "  File \"C:\\QA_GURU\\qa_guru_python_3_10\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\QA_GURU\\qa_guru_python_3_10\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\QA_GURU\\qa_guru_python_3_10\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 901, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\QA_GURU\\qa_guru_python_3_10\\conftest.py\", line 31, in open_browser\n    driver = webdriver.Remote(\n  File \"C:\\QA_GURU\\qa_guru_python_3_10\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 270, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\QA_GURU\\qa_guru_python_3_10\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 363, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"C:\\QA_GURU\\qa_guru_python_3_10\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 428, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\QA_GURU\\qa_guru_python_3_10\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 207, in check_response\n    raise exception_class(value)\n"}, "start": 1674293386313, "stop": 1674293386591}], "start": 1674293386313, "stop": 1674293386797}